project_id = "nunbhrmyihgtndryptai"

[functions.calculate-score]
verify_jwt = false

[functions.send-results-email]
verify_jwt = false

[functions.send-abandon-emails]
verify_jwt = false

[functions.fire-webhook]
verify_jwt = false

[functions.portal-auth]
verify_jwt = false

[functions.portal-notify]
verify_jwt = false
